---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: ansible_playbook
  playbook: tests/default.yml
  hosts: all
  ansible_verbose: true
  #ansible_version: 2.2.0
  #idempotency_test true

platforms:
  - name: ubuntu
    driver_config:
      provision_command:
        - apt-get install -y python-netaddr
      image: ubuntu:20.04
      platform: ubuntu

suites:
  - name: default
