#!/bin/sh
### BEGIN INIT INFO
# Provides:          ossec-remoted
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $network 
# Should-Stop:       $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop OSSEC HIDS
# Description:       Controls OSSEC HIDS daemons
#
### END INIT INFO

. /etc/ossec-init.conf
if [ "X${DIRECTORY}" = "X" ]; then
    DIRECTORY="/var/ossec"
fi

    
start() {
	${DIRECTORY}/bin/ossec-control start ossec-remoted
}

stop() {
	${DIRECTORY}/bin/ossec-control stop ossec-remoted
}

status() {
	${DIRECTORY}/bin/ossec-control status ossec-remoted
}


case "$1" in
  start)
	start
	;;
  stop) 
	stop
	;;
  restart)
	stop
	start
	;;
  status)
    status
	;;
  *)
	echo "*** Usage: $0 {start|stop|restart|status}"
	exit 1
esac
