version: '3'

services:
  wazuh-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${REGISTRY}:${IMG_TAG}
    ports:
      - "514:514"
      - "1514:1514"
    environment:
      - IMG_TAG=${IMG_TAG}
    working_dir: /opt/ansible/
    entrypoint:
      - ./entry.bash
