version: '3'

services:
  wazuh-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: quay.io/verygoodsecurity/ossec-server:${IMG_TAG}
    ports:
      - "514:514"
      - "1514:1514"
    environment:
      - IMG_TAG=${IMG_TAG}
      - ANSIBLE_ENABLE_TASK_DEBUGGER=True
    working_dir: /opt/ansible/
    entrypoint:
      - ./entry.bash
